# Generated by Django 3.2 on 2021-05-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('hotel', models.CharField(max_length=250)),
                ('number_of_person', models.IntegerField()),
                ('number_of_nights', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
