# Generated by Django 3.2 on 2021-05-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='rating',
        ),
    ]
