# Generated by Django 3.2 on 2021-05-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210512_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_nights',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_person',
            field=models.PositiveIntegerField(),
        ),
    ]
