# Generated by Django 3.2 on 2021-06-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_fix_Reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='card',
            field=models.DecimalField(decimal_places=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='valid_thru',
            field=models.DateField(null=True),
        ),
    ]
