# Generated by Django 3.2 on 2021-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card',
            field=models.DecimalField(decimal_places=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_thru',
            field=models.DateField(null=True),
        ),
    ]
