# Generated by Django 3.2 on 2021-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210512_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.DecimalField(decimal_places=0, max_digits=16, null=True, verbose_name='Card'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=200, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=100, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=7, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.CharField(max_length=200, verbose_name='Town'),
        ),
        migrations.AlterField(
            model_name='user',
            name='valid_thru',
            field=models.DateField(null=True, verbose_name='Valid date'),
        ),
    ]
