# Generated by Django 3.2 on 2021-06-16 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.DecimalField(blank=True, decimal_places=0, default=3323, max_digits=16, verbose_name='Card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='valid_thru',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Valid date'),
            preserve_default=False,
        ),
    ]
