# Generated by Django 3.2 on 2021-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='valid_thru',
            field=models.DateField(null=True, verbose_name='Valid date'),
        ),
    ]
