# Generated by Django 3.2 on 2021-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_eur', models.DecimalField(decimal_places=2, default=1.2, max_digits=2, max_length=10, verbose_name='euro/usd')),
            ],
        ),
    ]
