# Generated by Django 3.2 on 2021-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresses', models.CharField(max_length=2000, verbose_name='Adresses to send')),
                ('text', models.CharField(max_length=2000, verbose_name='Text')),
            ],
        ),
    ]
